vich_uploader:
    db_driver: orm


    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /images/pimento
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
